### ISSUE TITLE
Save in directory and format changes after config setting

### ISSUE THREAD

**Issue by questorfla** [appget/appget.packages#1826]
When installed with defaults all is fine.  After setting preferred option for general and hotkeys all still fine.  Changed the option for "save as" in order to give each screenshot the name i wanted when saved and many things went off.
The button to open folder of screenshots as well as the shortcut to it now opens to 'This PC' instead of the screenshot folder.   
The names that i give the screenshots are now showing "name.png.png".  The sample displayed in configuration does not show it like that and i cannot find a way to prevent it.  
![image](https://user-images.githubusercontent.com/19635177/44947726-40b55680-add7-11e8-80e3-81f3d313ded0.png)

I have tried every combination can see.  There is no way to leave "None" for the selection of filetype in case it is automatically done by another process.  I tried every combination i could think of.
Love the program and these are the only issues i have and i admit they are minor.  
If i leave the default settings
Attached is a zip of my config.ini file.  This is Ver 2.4 running on Win 10 Home X64
[myconfig.zip](https://github.com/appget/appget.packages/files/2342513/myconfig.zip)

If possible, it would be nice to name the file as saved instead of having to rename it after the fact.
And the button to open the folder they are stored in if it could stay where it started that would be helpful as well.  I believe all of this only happened when i opted for the "Save As" function

**Comment by kayone** [comment]
Hi @questorfla, I don't think your issue is related to AppGet, maybe you filed an issue here by accident?

**Comment by questorfla** [comment]
Sorry .  :(  True.  I mean to get on LightScreen.
