### ISSUE TITLE
[Package Request] Firealpaca

### ISSUE THREAD

**Issue by ArielRosenfeld** [appget/appget.packages#2244]
please add the painting app FireAlpaca

http://firealpaca.com/
download url http://firealpaca.com/download/win64

tried to use create but got
Request to https://xray.appget.net/xray?url=http:%2F%2Ffirealpaca.com%2Fdownload%2Fwin64 has timed out.

**Comment by kayone** [comment]
Done! https://github.com/appget/appget.packages/pull/2261

the reasons it was timing out was because download speed from their server is REALLY slow.
