### ISSUE TITLE
mkvtoolnix latest is not 29.0 but 31.0

### ISSUE THREAD

**Issue by igor-toporet** [appget/appget.packages#3004]
I've tried to create the manifest but it timed out
```
Couldn't submit manifest Request to https://octobot.appget.net/pr has timed out.
```
Attaching it here [mkvtoolnix.yaml.zip](https://github.com/appget/appget.packages/files/2921782/mkvtoolnix.yaml.zip)

**Comment by kayone** [comment]
Thanks Igor :D, I've updated the manifest to point to the direct downloads,

https://github.com/appget/appget.packages/pull/3015/files
