### ISSUE TITLE
SpeedFan 4.52

### ISSUE THREAD

**Issue by Gilbrilthor** [appget/appget.packages#3260]
I was unable to create a package for speedfan. It returned with failed. 400:BadRequest

**Comment by kayone** [comment]
there was an issue with the way we were making requests to their server, I've resolved the issue and also created and merged the package.

https://github.com/appget/appget.packages/pull/3281

Thanks for the heads-up.

**Comment by Gilbrilthor** [comment]
Thanks for the quick turnaround. The software is awesome!
