### ISSUE TITLE
PuTTY's manifest's website isn't the official one.

### ISSUE THREAD

**Issue by mercieralex** [appget/appget.packages#3423]
After some discussion [here](https://twitter.com/SwiftOnSecurity/status/510482857215922177?s=20) and [here](https://twitter.com/al45tair/status/1130057080377892864?s=20), I discovered PuTTY's website in its manifest isn't the official one.

I'd make a PR but I'm on my phone right now. I hope I can manage to do it later!

**Comment by kayone** [comment]
really appreciate the report. I've updated the manifest to point to the right place. just to give some context. 

Appget's users were never exposed to the unofficial version of putty, the `home` field is used for informational purposes only. I've confirmed the download links have always pointed to the right place.

**Comment by mercieralex** [comment]
Sorry for the late reply. Couldn't get back to you sooner.
Thank you for update and the context as well!
