### ISSUE TITLE
I can help with PR review / merging

### ISSUE THREAD

**Issue by ihodev** [appget/appget.packages#3469]
Things to check is described here: https://docs.appget.net/manifests/? Do you check something else? Tell me if you need help 😉

**Comment by kayone** [comment]
I really appreciate the offer! ❤️ 

most of the updates get automatically merged by @TheAppBot so it's pretty much a non-issue. The area we could use some help is adding new packages if they don't exist. 

I'm working on something where @TheAppBot  would also automatically open issues for packages that have problems. that would be another area where we could use some help but that is not ready yet.

**Comment by ihodev** [comment]
I see. In any case, ping me if you need any kind of help or something to test 🚀
