### ISSUE TITLE
imagemagick 7.0.8

### ISSUE THREAD

**Issue by zwickdeveloper** [appget/appget.packages#3509]
`Getting package imagemagick:latest
Beginning installation of 'imagemagick'

Downloading installer from https://imagemagick.org/download/binaries/ImageMagick-7.0.8-47-Q16-x64-dll.exe
Request to https://imagemagick.org/download/binaries/ImageMagick-7.0.8-47-Q16-x64-dll.exe failed. 404:NotFound`

**Comment by kayone** [comment]
sorry about that, the PR to fix this was created yesterday but wasn't merged yet. it should be fixed now.

https://github.com/appget/appget.packages/pull/3504/files
