### ISSUE TITLE
Add Laragon

### ISSUE THREAD

**Issue by tiuram0n** [appget/appget.packages#4346]
id: laragon
name: Laragon
version: 4.0.15
home: https://laragon.org/
repo: https://github.com/leokhoa/laragon
installMethod: Squirrel
installers:
- location: https://github.com/leokhoa/laragon/releases/download/4.0.15/laragon-wamp.x86.exe
  architecture: x86
- location: https://github.com/leokhoa/laragon/releases/download/4.0.15/laragon-full.exe
  architecture: x64

**Comment by kayone** [comment]
Added, in the future you can use `appget create` https://docs.appget.net/commands/#create to automatically create/submit packages.
